import type { Locale } from "@/i18n/config";

type UiCopy = {
  utility: string; call: string; bookRide: string; startReservation: string; services: string; fleet: string; serviceAreas: string; corporate: string; about: string; contact: string; privacy: string; terms: string; accessibility: string; popularRoutes: string; openMenu: string; closeMenu: string; footerIntro: string; instagramLabel: string; languageSelection: string; currentLanguage: (language: string) => string; switchToDark: string; switchToLight: string; mailingAddress: string; homeLabel: string; primaryNavigation: string; mobileNavigation: string; cookieLabel: string; cookieText: string; accept: string; decline: string;
};

export const ui: Record<Locale, UiCopy> = {
  en: {
    utility: "Private transportation • Central Florida", call: "Call", bookRide: "Book a ride", startReservation: "Start your reservation", services: "Services", fleet: "Fleet", serviceAreas: "Service areas", corporate: "Corporate", about: "About", contact: "Contact", privacy: "Privacy", terms: "Terms", accessibility: "Accessibility", popularRoutes: "Popular routes", openMenu: "Open menu", closeMenu: "Close menu", footerIntro: "Private transportation for airport, corporate, cruise and city-to-city travel.", instagramLabel: "Revival Transportation Group on Instagram", languageSelection: "Language selection", currentLanguage: (language) => `Current language: ${language}`, switchToDark: "Switch to dark mode", switchToLight: "Switch to light mode", mailingAddress: "Mailing address", homeLabel: "Revival Transportation Group home", primaryNavigation: "Primary navigation", mobileNavigation: "Mobile navigation", cookieLabel: "Cookie preferences", cookieText: "We use optional measurement cookies to understand website visits and improve advertising. You can accept or decline them.", accept: "Accept", decline: "No thanks",
  },
  es: {
    utility: "Transporte privado • Florida Central", call: "Llamar", bookRide: "Reservar un viaje", startReservation: "Inicia tu reserva", services: "Servicios", fleet: "Flota", serviceAreas: "Áreas de servicio", corporate: "Corporativo", about: "Acerca de", contact: "Contacto", privacy: "Privacidad", terms: "Términos", accessibility: "Accesibilidad", popularRoutes: "Rutas populares", openMenu: "Abrir menú", closeMenu: "Cerrar menú", footerIntro: "Transporte privado para viajes al aeropuerto, corporativos, cruceros y entre ciudades.", instagramLabel: "Revival Transportation Group en Instagram", languageSelection: "Selección de idioma", currentLanguage: (language) => `Idioma actual: ${language}`, switchToDark: "Cambiar a modo oscuro", switchToLight: "Cambiar a modo claro", mailingAddress: "Dirección postal", homeLabel: "Inicio de Revival Transportation Group", primaryNavigation: "Navegación principal", mobileNavigation: "Navegación móvil", cookieLabel: "Preferencias de cookies", cookieText: "Usamos cookies de medición opcionales para conocer las visitas al sitio y mejorar la publicidad. Puedes aceptarlas o rechazarlas.", accept: "Aceptar", decline: "No, gracias",
  },
  pt: {
    utility: "Transporte privativo • Flórida Central", call: "Ligar", bookRide: "Reserve sua viagem", startReservation: "Inicie sua reserva", services: "Serviços", fleet: "Frota", serviceAreas: "Áreas de serviço", corporate: "Corporativo", about: "Sobre", contact: "Contato", privacy: "Privacidade", terms: "Termos", accessibility: "Acessibilidade", popularRoutes: "Rotas populares", openMenu: "Abrir menu", closeMenu: "Fechar menu", footerIntro: "Transporte privativo para aeroporto, viagens corporativas, cruzeiros e deslocamentos entre cidades.", instagramLabel: "Revival Transportation Group no Instagram", languageSelection: "Seleção de idioma", currentLanguage: (language) => `Idioma atual: ${language}`, switchToDark: "Mudar para modo escuro", switchToLight: "Mudar para modo claro", mailingAddress: "Endereço postal", homeLabel: "Início da Revival Transportation Group", primaryNavigation: "Navegação principal", mobileNavigation: "Navegação móvel", cookieLabel: "Preferências de cookies", cookieText: "Usamos cookies opcionais de medição para entender as visitas ao site e melhorar a publicidade. Você pode aceitá-los ou recusá-los.", accept: "Aceitar", decline: "Não, obrigado",
  },
};

export function getUi(locale: Locale) { return ui[locale]; }
