import type { Locale } from "@/i18n/config";

type UiCopy = {
  utility: string; call: string; bookRide: string; startReservation: string; services: string; fleet: string; serviceAreas: string; corporate: string; about: string; contact: string; privacy: string; terms: string; accessibility: string; popularRoutes: string; openMenu: string; closeMenu: string; footerIntro: string; instagramLabel: string; languageSelection: string; currentLanguage: (language: string) => string; switchToDark: string; switchToLight: string; mailingAddress: string; homeLabel: string; primaryNavigation: string; mobileNavigation: string; cookieLabel: string; cookieText: string; acceptAll: string; rejectNonEssential: string; cookieManage: string; cookieSave: string; cookieNecessary: string; cookieNecessaryDetail: string; cookieAnalytics: string; cookieAnalyticsDetail: string; cookieAdvertising: string; cookieAdvertisingDetail: string; cookiePreferences: string;
};

export const ui: Record<Locale, UiCopy> = {
  en: {
    utility: "Private transportation • Central Florida", call: "Call", bookRide: "Book a ride", startReservation: "Start your reservation", services: "Services", fleet: "Fleet", serviceAreas: "Service areas", corporate: "Corporate", about: "About", contact: "Contact", privacy: "Privacy", terms: "Terms", accessibility: "Accessibility", popularRoutes: "Popular routes", openMenu: "Open menu", closeMenu: "Close menu", footerIntro: "Private transportation for airport, corporate, cruise and city-to-city travel.", instagramLabel: "Revival Transportation Group on Instagram", languageSelection: "Language selection", currentLanguage: (language) => `Current language: ${language}`, switchToDark: "Switch to dark mode", switchToLight: "Switch to light mode", mailingAddress: "Mailing address", homeLabel: "Revival Transportation Group home", primaryNavigation: "Primary navigation", mobileNavigation: "Mobile navigation", cookieLabel: "Cookie preferences", cookieText: "Choose which optional cookies can help us measure visits and improve advertising. Necessary cookies are always on.", acceptAll: "Accept all", rejectNonEssential: "Reject non-essential", cookieManage: "Manage preferences", cookieSave: "Save preferences", cookieNecessary: "Necessary", cookieNecessaryDetail: "Required for essential website functions.", cookieAnalytics: "Analytics", cookieAnalyticsDetail: "Helps us understand website visits.", cookieAdvertising: "Advertising", cookieAdvertisingDetail: "Helps measure advertising performance.", cookiePreferences: "Cookie preferences",
  },
  es: {
    utility: "Transporte privado • Florida Central", call: "Llamar", bookRide: "Reservar un viaje", startReservation: "Inicia tu reserva", services: "Servicios", fleet: "Flota", serviceAreas: "Áreas de servicio", corporate: "Corporativo", about: "Acerca de", contact: "Contacto", privacy: "Privacidad", terms: "Términos", accessibility: "Accesibilidad", popularRoutes: "Rutas populares", openMenu: "Abrir menú", closeMenu: "Cerrar menú", footerIntro: "Transporte privado para viajes al aeropuerto, corporativos, cruceros y entre ciudades.", instagramLabel: "Revival Transportation Group en Instagram", languageSelection: "Selección de idioma", currentLanguage: (language) => `Idioma actual: ${language}`, switchToDark: "Cambiar a modo oscuro", switchToLight: "Cambiar a modo claro", mailingAddress: "Dirección postal", homeLabel: "Inicio de Revival Transportation Group", primaryNavigation: "Navegación principal", mobileNavigation: "Navegación móvil", cookieLabel: "Preferencias de cookies", cookieText: "Elige qué cookies opcionales pueden ayudarnos a medir las visitas y mejorar la publicidad. Las cookies necesarias siempre están activas.", acceptAll: "Aceptar todas", rejectNonEssential: "Rechazar no esenciales", cookieManage: "Administrar preferencias", cookieSave: "Guardar preferencias", cookieNecessary: "Necesarias", cookieNecessaryDetail: "Requeridas para las funciones esenciales del sitio.", cookieAnalytics: "Analíticas", cookieAnalyticsDetail: "Nos ayudan a comprender las visitas al sitio.", cookieAdvertising: "Publicidad", cookieAdvertisingDetail: "Ayuda a medir el rendimiento de la publicidad.", cookiePreferences: "Preferencias de cookies",
  },
  pt: {
    utility: "Transporte privativo • Flórida Central", call: "Ligar", bookRide: "Reserve sua viagem", startReservation: "Inicie sua reserva", services: "Serviços", fleet: "Frota", serviceAreas: "Áreas de serviço", corporate: "Corporativo", about: "Sobre", contact: "Contato", privacy: "Privacidade", terms: "Termos", accessibility: "Acessibilidade", popularRoutes: "Rotas populares", openMenu: "Abrir menu", closeMenu: "Fechar menu", footerIntro: "Transporte privativo para aeroporto, viagens corporativas, cruzeiros e deslocamentos entre cidades.", instagramLabel: "Revival Transportation Group no Instagram", languageSelection: "Seleção de idioma", currentLanguage: (language) => `Idioma atual: ${language}`, switchToDark: "Mudar para modo escuro", switchToLight: "Mudar para modo claro", mailingAddress: "Endereço postal", homeLabel: "Início da Revival Transportation Group", primaryNavigation: "Navegação principal", mobileNavigation: "Navegação móvel", cookieLabel: "Preferências de cookies", cookieText: "Escolha quais cookies opcionais podem nos ajudar a medir visitas e melhorar a publicidade. Os cookies necessários ficam sempre ativos.", acceptAll: "Aceitar todos", rejectNonEssential: "Recusar não essenciais", cookieManage: "Gerenciar preferências", cookieSave: "Salvar preferências", cookieNecessary: "Necessários", cookieNecessaryDetail: "Necessários para as funções essenciais do site.", cookieAnalytics: "Análises", cookieAnalyticsDetail: "Ajuda a entender as visitas ao site.", cookieAdvertising: "Publicidade", cookieAdvertisingDetail: "Ajuda a medir o desempenho da publicidade.", cookiePreferences: "Preferências de cookies",
  },
};

export function getUi(locale: Locale) { return ui[locale]; }
