import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/json-ld";
import { Breadcrumbs, PageHero, PrimaryCta, Section, SectionHeading } from "@/components/site-components";
import { airports, findAirport } from "@/content/data";
import { breadcrumbSchema, pageMetadata } from "@/lib/seo";
import { absoluteUrl } from "@/lib/site";

export function generateStaticParams() { return airports.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const airport = findAirport(slug); return airport ? pageMetadata(`${airport.code} Airport Transportation`, airport.intro, `/airports/${airport.slug}`) : {}; }); }
export default async function AirportPage({ params }: { params: Promise<{ slug: string }> }) { const airport = findAirport((await params).slug); if (!airport) notFound(); const path = `/airports/${airport.slug}`; const breadcrumbs = [{ label: "Home", href: "/" }, { label: "Service areas", href: "/service-areas" }, { label: airport.code }]; const airportSchema = { "@context": "https://schema.org", "@type": "Service", name: `${airport.code} Airport Transportation`, description: airport.intro, url: absoluteUrl(path), provider: { "@id": absoluteUrl("/#transportation-service") }, areaServed: { "@type": "Airport", name: airport.name, iataCode: airport.code } }; return <><JsonLd data={[airportSchema, breadcrumbSchema(breadcrumbs, path)]} /><div className="container crumb-wrap"><Breadcrumbs items={breadcrumbs} /></div><PageHero eyebrow={`${airport.code} airport transportation`} title={`Private travel for ${airport.name}.`} intro={airport.intro}><PrimaryCta placement={`airport-${airport.slug}`} /></PageHero><Section><div className="container split-copy"><div><SectionHeading eyebrow="Plan the details" title="Share what makes your trip unique." /><p>Airport travel goes more smoothly when the reservation includes the flight timing, final destination, passenger count and luggage needs.</p></div><ol className="number-list">{airport.details.map((detail, index) => <li key={detail}><span>0{index + 1}</span>{detail}</li>)}</ol></div></Section><Section className="soft-section"><div className="container three-note-grid"><div><span>01</span><h2>Arrivals</h2><p>Include your flight and requested pickup details for a confirmed travel plan.</p></div><div><span>02</span><h2>Departures</h2><p>Share your flight timing and pickup location early to review availability.</p></div><div><span>03</span><h2>Connections</h2><p>Airport-to-port and airport-to-resort travel can be planned with your trip details.</p></div></div></Section></>; }
